#Use the official node.js image
From node:14

#Create and change to the app directory
WORKDIR /usr/src/app

#Copy application deendency manifests to the container image
COPY package*.json ./

#Install production dependencies
RUN npm install

#Copy local code to the container image
COPY . .

#Run the web service on container startup
CMD ["node", "index.js"]
